version: "3"
# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio
    container_name: al-folio-website
    command: bash -c "
      bundle install &&
      rm -f Gemfile.lock
      && bundler exec jekyll serve --watch --port=8080 --host=127.0.0.1 --livereload --verbose --trace"
    ports:
      - 8080:8080
    volumes:
      - .:/srv/jekyll
  
  build:
    image: amirpourmand/al-folio
    container_name: al-folio-website
    command: bash -c "
      bundle install &&
      rm -f Gemfile.lock
      && bundler exec jekyll build --lsi"
    volumes:
      - .:/srv/jekyll
      - ./_site:/srv/jekyll/_site
    working_dir: /srv/jekyll
